services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
    volumes:
      - ./kafka_data:/var/lib/kafka/data

#  # Tùy chọn: Kafdrop là một Kafka UI để quản lý Kafka từ giao diện web
#  kafdrop:
#    image: obsidiandynamics/kafdrop:latest
#    container_name: kafdrop
#    environment:
#      KAFKA_BROKERCONNECT: kafka:9092  # Kết nối tới Kafka broker
#      JVM_OPTS: "-Xms32M -Xmx64M"
#    ports:
#      - "9000:9000"  # Expose giao diện web của Kafdrop
#    depends_on:
#      - kafka  # Đảm bảo Kafka khởi động trước Kafdrop
